services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-experiment
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: experiment
    ports:
      - "5681:5672"
      - "15681:15672"